import { TREE_RIGHT_CLICK_MENUS } from '@/utils/menus/treeRightClickMenusItem.js'

export const treeRightClickMappings = {
  DATASOURCE: [
    TREE_RIGHT_CLICK_MENUS.DATASOURCE_CREATE,
    TREE_RIGHT_CLICK_MENUS.DATASOURCE_EDIT,
    TREE_RIGHT_CLICK_MENUS.DIVIDER,
    TREE_RIGHT_CLICK_MENUS.DATASOURCE_REFRESH,
  ],
}
